### PR TITLE
Update to 2.0.0

### PR DESCRIPTION
**Pull request by chohner**

### CODE REVIEW

**Comment by chohner** [comment]
seems like html5lib keeps complaining about py36 :(

**Comment by dhirschfeld** [comment]
I built the package with this recipe so looks like all the deps are available now. The CI probably just needs to be restarted.
```
conda install -c dhirschfeld bleach
```

**Comment by chohner** [comment]
Hm seems like a can't restart on circle due to missing permissions. Let's see what travis and appveyor say

**Comment by chohner** [comment]
Only failing on circle with

```The following specifications were found to be in conflict:
  - bleach 2.0.0 py36_0```

**Comment by chohner** [comment]
@jakirkham could you or someone who knows what's going on have a look?

**Pull request closed without merging**
